name: CI

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["*"]

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: "Set pnpm"
              uses: pnpm/action-setup@v4.0.0
              with:
                  version: 6.35.1

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 14.x
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Run lint
              run: pnpm run lint

            - name: Build test
              run: pnpm run build
